# Generated by Django 5.0 on 2024-11-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0003_alter_booking_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urban.consumer'),
        ),
    ]
