# Generated by Django 5.0 on 2024-11-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0004_alter_booking_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urban.worker'),
        ),
    ]
