# Generated by Django 5.0 on 2024-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0005_payment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='worker',
            field=models.CharField(default='hai', max_length=16),
        ),
    ]
